# In finsight/server/docker-compose.yml

version: '3.8'

services:
  # Our React Frontend Service
  client:
    build:
      context: ../client
    volumes:
      - ../client:/app
      - /app/node_modules # <--- This line is the crucial fix
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

  # Our Node.js Backend Service
  server:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - AI_SERVICE_URL=http://ai-service:8000
    depends_on:
      - db
      - ai-service

  # Our PostgreSQL Database Service
  db:
    image: postgres:16-alpine
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=finsight
    ports:
      - "5432:5432"

  # Our Python AI Service
  ai-service:
    build:
      context: ../ai-service
    volumes:
      - ../ai-service:/ai_app
    ports:
      - "8000:8000"

volumes:
  postgres-db:
